-- Script de criação do banco PostoABC (Firebird 3)
CREATE DATABASE 'postoabc.fdb' USER 'SYSDBA' PASSWORD 'MASTERKEY';

CREATE TABLE Combustivel (
  IdCombustivel INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Descricao VARCHAR(30),
  Valor NUMERIC(10,2)
);

CREATE TABLE Tanque (
  IdTanque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Descricao VARCHAR(30),
  IdCombustivel INTEGER NOT NULL,
  FOREIGN KEY (IdCombustivel) REFERENCES Combustivel (IdCombustivel)  
);


CREATE TABLE Bomba (
  IdBomba INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Descricao VARCHAR(50)
);


CREATE TABLE BombaTanque (
  IdBombaTanque INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IdBomba INTEGER NOT NULL,
  IdTanque INTEGER NOT NULL,
  FOREIGN KEY (IdBomba) REFERENCES Bomba (IdBomba),
  FOREIGN KEY (IdTanque) REFERENCES Tanque (IdTanque)
);


CREATE TABLE Abastecimento (
  IdAbastecimento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  IdBombaTanque INTEGER NOT NULL,
  DataAbast DATE,
  Litros NUMERIC(10,2),
  Valor NUMERIC(10,2),
  Imposto NUMERIC(10,2),
  FOREIGN KEY (IdBombaTanque) REFERENCES BombaTanque (IdBombaTanque)
);



INSERT INTO Combustivel (Descricao, Valor) VALUES ('Gasolina', 6.14 );
INSERT INTO Combustivel (Descricao, Valor) VALUES ('Diesel', 5.33);

INSERT INTO Tanque (Descricao, IdCombustivel) VALUES ('Tanque 1', 1);
INSERT INTO Tanque (Descricao, IdCombustivel) VALUES ('Tanque 2', 2);

INSERT INTO Bomba (Descricao) VALUES ('Bomba 1');
INSERT INTO Bomba (Descricao) VALUES ('Bomba 2');
INSERT INTO Bomba (Descricao) VALUES ('Bomba 3');
INSERT INTO Bomba (Descricao) VALUES ('Bomba 4');

INSERT INTO BombaTanque (IdTanque, IdBomba) VALUES (1, 1);
INSERT INTO BombaTanque (IdTanque, IdBomba) VALUES (2, 2);
INSERT INTO BombaTanque (IdTanque, IdBomba) VALUES (1, 3);
INSERT INTO BombaTanque (IdTanque, IdBomba) VALUES (2, 4);